### ISSUE TITLE
RSA 2048: minimum=127ms, average=120ms

### ISSUE THREAD

**Issue by julianladisch** [mozilla/wikimo_opsec#21]
This is in https://github.com/mozilla/wikimo_opsec/blob/master/Security/Guidelines/OpenSSH.mediawiki:

    ! Client key !! Minimum !! Maximum !! Average
    | RSA 2048 || 127ms || 129ms || 120ms

The minimum cannot be bigger than the average.

**Comment by gdestuynder** [comment]
Thanks, fixed by https://github.com/mozilla/wikimo_opsec/commit/5f1469c38dabe36ec23a8e485b02ecbf484b9727
