### ISSUE TITLE
Web Security Guidelines rename?

### ISSUE THREAD

**Issue by amuntner** [mozilla/wikimo_opsec#42]
"Website Security Guidelines" is an overly overly broad for what they describe, our goals are much more narrow. 

April's goal was to make them generic, usable by the world, and focused on headers, I am in complete agreement with this. 

 "HTTP Header Security Guidelines" or something like it would be more appropriate.

**Comment by marumari** [comment]
I should note that there are at least some things (contribute.json, a lot of CORS stuff, TLS config) that have nothing to do with HTTP headers.

**Comment by marumari** [comment]
I still haven't heard any super convincing arguments as to why to rename it, especially since @amuntner's justifications for changing them aren't accurate.

**Comment by amuntner** [comment]
April, I think there was some miscommunication.

I remember your describing your vision for this project - that it was to be a list of guidelines that was not too Mozilla-specific and would be usable by the wider world. You intended for this to be a guideline that would inform Mozilla standards and weren't sure at first whether contribute.json should be here or a Mozilla standard. I thought your approach was right and I and would be happy with contribute.json in either or both locations.

Initially the guideline standard list was geared towards Web server/web site/service configuration issues. I didn't say "exclusively about headers," I said "focused on." Even though CORS problems are mostly XML related, the user agent and server signal communication in headers. TLS config isn't all headers, but HPKP, HSTS, and CORS are all signalled and negotiated through headers. There's also Contribute.json and robots.txt. 

So the document is called Guidelines, but says "All Mozilla sites and deployments are expected to follow the recommendations below. Use of these recommendations by the public is strongly encouraged." Is it a guideline? I see that now your intent is to make it a lot more inclusive of other kinds of issues than it already is, such as the queued work for sql injection discussion, and agree with this approach. The right place for the standard is probably in Mana with a copy on the Wiki, in @gdestuynder's standards format, keeping the Wiki version the guideline that informs our standard. 

You have seen https://wiki.mozilla.org/WebAppSec/Secure_Coding_Guidelines I'm pretty sure. I like a lot of the elements you used in your page like the cheat sheet approach and layout which are really good and very useful. What do you think about an effort at reviewing the older Secure Coding guidelines, seeing what parts are still good, integrating those parts into your document, and updating the parts of the old doc, that need it? We could track it with the Trello board.

**Comment by marumari** [comment]
Sure, but making them focused on headers was never one of my goals?  It's only getting smaller in time too, as CSP subsumes a lot of them.

In any case, integrating more of the secure coding stuff had always been my list of things to do, I'm just short on time.  But feel free to open up an issue (or issues) for sections of the those standards that you would like to have integrated, and we can make that happen!
