### ISSUE TITLE
sync up changes from https://wiki.mozilla.org/index.php?title=Security/OpSec&diff=next&oldid=1086457

### ISSUE THREAD

**Issue by gdestuynder** [mozilla/wikimo_opsec#5]
https://wiki.mozilla.org/index.php?title=Security/OpSec&diff=next&oldid=1086457 are the changes

**Comment by jeffbryner** [comment]
doh

**Comment by gdestuynder** [comment]
fixed by https://github.com/mozilla/wikimo_opsec/pull/6
